import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import RewardContainer from "@/components/Containers/RewardContainer";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "DenZ for GenZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Toaster position="top-right" reverseOrder={false} />
      <body className={poppins.variable}>{children}</body>
      <body className={poppins.variable}>
        <RewardContainer>{children}</RewardContainer>
      </body>
    </html>
  );
}
